/**
 * Renders an AGENTS.md / CLAUDE.md operating-notes file from what DashClaw has
 * learned: the loop engine's distilled `learning_recommendations` (guidance +
 * confidence + sample size) and the recorded `decisions` ledger (what worked,
 * what didn't, and why).
 *
 * Pure and side-effect-free so it is unit-testable; the route supplies the rows
 * and a timestamp. AGENTS.md and CLAUDE.md differ only in title/preamble — both
 * are markdown an agent reads at session start.
 */

export type LearningExportFormat = 'agents' | 'claude';

export interface ExportDecision {
  decision?: unknown;
  context?: unknown;
  reasoning?: unknown;
  outcome?: unknown;
  confidence?: unknown;
  agent_id?: unknown;
}

export interface ExportRecommendation {
  agent_id?: unknown;
  action_type?: unknown;
  confidence?: unknown;
  sample_size?: unknown;
  hints?: unknown;
  guidance?: unknown;
}

export interface RenderLearningExportOptions {
  format: LearningExportFormat;
  decisions?: ExportDecision[];
  recommendations?: ExportRecommendation[];
  generatedAt?: string;
}

function str(v: unknown): string {
  return v == null ? '' : String(v).trim();
}

function num(v: unknown): number | null {
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

/** Coerce a single guidance entry (string or {text|message|hint|...}) to text. */
function guidanceText(item: unknown): string {
  if (item == null) return '';
  if (typeof item === 'string') return item.trim();
  if (typeof item === 'object') {
    const o = item as Record<string, unknown>;
    return str(o.text || o.message || o.hint || o.guidance || o.title || '');
  }
  return str(item);
}

function guidanceList(guidance: unknown): string[] {
  if (Array.isArray(guidance)) {
    return guidance.map(guidanceText).filter(Boolean);
  }
  const single = guidanceText(guidance);
  return single ? [single] : [];
}

/** Render the non-empty hints object as a compact "key: value" signal line. */
function hintLine(hints: unknown): string {
  if (!hints || typeof hints !== 'object' || Array.isArray(hints)) return '';
  const parts: string[] = [];
  for (const [k, v] of Object.entries(hints as Record<string, unknown>)) {
    const val = str(v);
    if (val) parts.push(`${k}: ${val}`);
  }
  return parts.length ? parts.join(' · ') : '';
}

function isSuccess(outcome: string): boolean {
  return /^(success|succeeded|passed|ok|done|completed)$/i.test(outcome);
}

function isFailure(outcome: string): boolean {
  return /^(fail|failed|failure|error|blocked|invalidated|denied)$/i.test(outcome);
}

export function renderLearningExport(opts: RenderLearningExportOptions): string {
  const { format } = opts;
  const decisions = opts.decisions ?? [];
  const recommendations = opts.recommendations ?? [];
  const generatedAt = opts.generatedAt ?? '';

  const isClaude = format === 'claude';
  const title = isClaude ? 'Project Guidance for Claude Code' : 'Agent Operating Notes';
  const stamp = generatedAt ? ` on ${generatedAt}` : '';

  const out: string[] = [];
  out.push(`# ${title}`);
  out.push('');
  out.push(
    `<!-- Generated by DashClaw${stamp} from ${decisions.length} recorded decision(s) ` +
      `and ${recommendations.length} learned pattern(s). Regenerate any time from the ` +
      `Learning page or \`GET /api/learning/export\`. Edit freely — DashClaw will not overwrite it. -->`,
  );
  out.push('');
  out.push(
    'This file distills what DashClaw has observed from your agents’ governed activity — ' +
      'patterns worth repeating, decisions that worked, and pitfalls to avoid. Read it at the ' +
      'start of a session and treat it as accumulated operating knowledge.',
  );
  out.push('');

  // --- Learned patterns (the loop engine's distilled recommendations) --------
  out.push('## Learned patterns');
  out.push('');
  const recs = [...recommendations].sort((a, b) => (num(b.confidence) ?? 0) - (num(a.confidence) ?? 0));
  const renderedRecs = recs
    .map((r) => {
      const guidance = guidanceList(r.guidance);
      if (guidance.length === 0) return '';
      const actionType = str(r.action_type) || 'general';
      const agent = str(r.agent_id);
      const conf = num(r.confidence);
      const samples = num(r.sample_size);
      const meta: string[] = [];
      if (conf != null) meta.push(`${Math.round(conf)}% confidence`);
      if (samples != null) meta.push(`${samples} sample${samples === 1 ? '' : 's'}`);
      if (agent) meta.push(`agent: ${agent}`);
      const header = `### ${actionType}${meta.length ? ` — ${meta.join(', ')}` : ''}`;
      const bullets = guidance.map((g) => `- ${g}`);
      const hl = hintLine(r.hints);
      const lines = [header, '', ...bullets];
      if (hl) {
        lines.push('');
        lines.push(`_Signals: ${hl}_`);
      }
      return lines.join('\n');
    })
    .filter(Boolean);

  if (renderedRecs.length) {
    out.push(renderedRecs.join('\n\n'));
  } else {
    out.push(
      '_No learned patterns yet. DashClaw builds these automatically as your agents record ' +
        'more governed actions — run the learning loop once there is enough history._',
    );
  }
  out.push('');

  // --- Decisions that worked -------------------------------------------------
  const successes = decisions.filter((d) => isSuccess(str(d.outcome)) && str(d.decision));
  if (successes.length) {
    out.push('## Decisions that worked');
    out.push('');
    for (const d of successes.slice(0, 50)) {
      const decision = str(d.decision);
      const context = str(d.context);
      const reasoning = str(d.reasoning);
      let line = `- **${decision}**`;
      if (context) line += ` — ${context}`;
      if (reasoning) line += ` _(why: ${reasoning})_`;
      out.push(line);
    }
    out.push('');
  }

  // --- What to avoid ---------------------------------------------------------
  const failures = decisions.filter((d) => isFailure(str(d.outcome)) && str(d.decision));
  if (failures.length) {
    out.push('## What to avoid');
    out.push('');
    for (const d of failures.slice(0, 50)) {
      const decision = str(d.decision);
      const context = str(d.context);
      let line = `- **${decision}** did not work`;
      if (context) line += `: ${context}`;
      out.push(line);
    }
    out.push('');
  }

  out.push('---');
  out.push(
    `*${decisions.length} decision(s) · ${recommendations.length} learned pattern(s) · generated by DashClaw governance.*`,
  );
  out.push('');

  return out.join('\n');
}
