#!/usr/bin/env python3
"""Auto-generated by AgentLens. Cost-limit guard hook for Claude Code.

Project: C--Projects-DashClaw
Limit: $80.55 per session (≈3× project median $26.85)
Source session: acec7ebd-b7d3-4e21-8582-f9617e66b654

Install: register this script as a PostToolUse hook in settings.json.
"""
import json, os, sys, time, pathlib, traceback

LIMIT_USD = 80.5506
STATE_DIR = pathlib.Path.home() / ".claude-agentlens"
STATE_DIR.mkdir(exist_ok=True)

# Pricing per 1M tokens. Mirror of src/pricing.js — update both together.
PRICES = {
    "claude-opus-4-7":   {"input": 15.0, "output": 75.0, "cache_write": 18.75, "cache_read": 1.5},
    "claude-sonnet-4-6": {"input":  3.0, "output": 15.0, "cache_write":  3.75, "cache_read": 0.3},
    "claude-haiku-4-5":  {"input":  1.0, "output":  5.0, "cache_write":  1.25, "cache_read": 0.1},
}
DEFAULT_PRICE = {"input": 3.0, "output": 15.0, "cache_write": 3.75, "cache_read": 0.3}

def _price_for(model):
    if not model: return DEFAULT_PRICE
    m = model.split("[")[0]
    return PRICES.get(m, DEFAULT_PRICE)

def _state_path(session_id):
    safe = "".join(c for c in (session_id or "default") if c.isalnum() or c in "-_") or "default"
    return STATE_DIR / f"cost-limit-{safe}.json"

def main():
    raw = sys.stdin.read() or "{}"
    try:
        event = json.loads(raw)
    except Exception:
        return 0
    usage = event.get("usage") or event.get("response", {}).get("usage") or {}
    model = event.get("model") or event.get("response", {}).get("model")
    if not usage:
        return 0
    p = _price_for(model)
    cost = (
        (usage.get("input_tokens", 0) or 0)            * p["input"]
      + (usage.get("output_tokens", 0) or 0)           * p["output"]
      + (usage.get("cache_creation_input_tokens", 0) or 0) * p["cache_write"]
      + (usage.get("cache_read_input_tokens", 0) or 0)     * p["cache_read"]
    ) / 1_000_000.0
    session_id = event.get("session_id") or event.get("sessionId") or "default"
    state_file = _state_path(session_id)
    try:
        state = json.loads(state_file.read_text()) if state_file.exists() else {"total": 0.0}
    except Exception:
        state = {"total": 0.0}
    state["total"] = float(state.get("total", 0.0)) + cost
    state["updated"] = time.time()
    try:
        state_file.write_text(json.dumps(state))
    except Exception:
        pass
    if state["total"] >= LIMIT_USD:
        sys.stderr.write(
            f"agentlens cost-limit guard: session cost is ${state['total']:.2f} which exceeds the limit of ${LIMIT_USD:.2f}. "
            f"Stop, summarize what you have, and restart with a tighter goal.\n"
        )
        return 2
    return 0

if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception:
        traceback.print_exc(file=sys.stderr)
        sys.exit(0)

# Default limit ≈ $80.55 (3× project median, an estimate — adjust before strict mode).
# Install snippet:
# {
#   "hooks": {
#     "PostToolUse": [
#       {
#         "matcher": "*",
#         "hooks": [
#           {
#             "type": "command",
#             "command": "python \"C:\\Projects\\DashClaw\\.claude\\hooks\\agentlens-cost-limit-guard.py\""
#           }
#         ]
#       }
#     ]
#   }
# }
