#!/usr/bin/env python3
"""Auto-generated by AgentLens. Secret-output guard hook for Claude Code.

Project: C--Projects-DashClaw
Source session: acec7ebd-b7d3-4e21-8582-f9617e66b654

Scans the proposed content of a Write/Edit tool call for obvious secret
patterns. If any match, the hook exits 2 with stderr explaining what was
flagged. Patterns mirror AgentLens's redaction layer.
"""
import json, re, sys, traceback

PATTERNS = [
    (re.compile(r"sk_test_[A-Za-z0-9]{8,}"), "stripe_test"),
    (re.compile(r"sk_live_[A-Za-z0-9]{8,}"), "stripe_live"),
    (re.compile(r"whsec_[A-Za-z0-9]{8,}"), "stripe_webhook"),
    (re.compile(r"sk-ant-[A-Za-z0-9_\-]{20,}"), "anthropic_key"),
    (re.compile(r"(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{20,}"), "github_pat"),
    (re.compile(r"AKIA[0-9A-Z]{16}"), "aws_access"),
    (re.compile(r"-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----"), "private_key"),
]

def main():
    raw = sys.stdin.read() or "{}"
    try: event = json.loads(raw)
    except Exception: return 0
    if event.get("tool_name") not in ("Write", "Edit", "MultiEdit", "Bash"): return 0
    inp = event.get("tool_input") or {}
    haystack = ""
    for k in ("content", "new_string", "command", "stdin"):
        v = inp.get(k)
        if isinstance(v, str): haystack += "\n" + v
    hits = []
    for pat, name in PATTERNS:
        if pat.search(haystack): hits.append(name)
    if hits:
        sys.stderr.write(
            "agentlens secret-output guard blocked this tool call.\n"
            f"  matched: {sorted(set(hits))}\n"
            "  rewrite the content to redact the secret, or read it from a local env file instead.\n"
        )
        return 2
    return 0

if __name__ == "__main__":
    try: sys.exit(main())
    except Exception:
        traceback.print_exc(file=sys.stderr); sys.exit(0)
