#!/usr/bin/env python3
"""Auto-generated by AgentLens. Stuck-loop guard hook for Claude Code.

Project: C--Projects-DashClaw
Threshold: 5 consecutive identical tool calls
Source session: acec7ebd-b7d3-4e21-8582-f9617e66b654

Install: register this script as a PreToolUse hook in settings.json.
See the install snippet returned alongside this file.
"""
import json, os, sys, time, pathlib, traceback

THRESHOLD = 5
STATE_DIR = pathlib.Path.home() / ".claude-agentlens"
STATE_DIR.mkdir(exist_ok=True)

def _state_path(session_id):
    safe = "".join(c for c in (session_id or "default") if c.isalnum() or c in "-_") or "default"
    return STATE_DIR / f"stuck-loop-{safe}.json"

def main():
    raw = sys.stdin.read() or "{}"
    try:
        event = json.loads(raw)
    except Exception:
        return 0  # fail-open on malformed input
    tool_name = event.get("tool_name") or event.get("tool", {}).get("name")
    session_id = event.get("session_id") or event.get("sessionId") or "default"
    if not tool_name:
        return 0
    state_file = _state_path(session_id)
    try:
        state = json.loads(state_file.read_text()) if state_file.exists() else {}
    except Exception:
        state = {}
    if state.get("last") == tool_name:
        state["count"] = int(state.get("count", 1)) + 1
    else:
        state["last"] = tool_name
        state["count"] = 1
    state["updated"] = time.time()
    try:
        state_file.write_text(json.dumps(state))
    except Exception:
        pass
    if state["count"] >= THRESHOLD:
        sys.stderr.write(
            f"agentlens stuck-loop guard: '{tool_name}' has run {state['count']} times in a row. "
            f"Threshold {THRESHOLD} reached. Consider tightening the goal or checkpointing a plan.\n"
        )
        try: state_file.unlink()
        except Exception: pass
        return 2  # exit code 2 → Claude treats stderr as a hard error
    return 0

if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception:
        traceback.print_exc(file=sys.stderr)
        sys.exit(0)

# Install snippet (settings.json):
# {
#   "hooks": {
#     "PreToolUse": [
#       {
#         "matcher": "*",
#         "hooks": [
#           {
#             "type": "command",
#             "command": "python \"C:\\Projects\\DashClaw\\.claude\\hooks\\agentlens-stuck-loop-guard.py\""
#           }
#         ]
#       }
#     ]
#   }
# }
