#!/usr/bin/env python3
"""SessionStart announcer: prints an index of codebase maps as context.

Stdout from a SessionStart hook is added to the session context. Output is
phrased as factual project information (not commands) so it is treated as
context rather than tripping prompt-injection defenses.
"""
import glob, os

here = os.path.dirname(os.path.abspath(__file__))
claude_dir = os.path.dirname(here)            # <repo>/.claude
maps = sorted(glob.glob(os.path.join(claude_dir, "CODEBASE_MAP*.md")))
if maps:
    print("Codebase maps for this repo (generated by the codebase-map skill):")
    for m in maps:
        print(f"- {os.path.join('.claude', os.path.basename(m))}")
    print("Each documents a package's architecture, data model, public "
          "contracts, and invariants.")
