import { describe, it, expect } from 'vitest';
import { renderLearningExport } from '../../app/lib/learning-export';

describe('renderLearningExport', () => {
  it('renders an empty state when there is no learning yet', () => {
    const md = renderLearningExport({ format: 'agents', decisions: [], recommendations: [] });
    expect(md).toContain('# Agent Operating Notes');
    expect(md).toContain('No learned patterns yet');
    expect(md).toContain('0 decision(s) · 0 learned pattern(s)');
    // No decision sections when there are none
    expect(md).not.toContain('## Decisions that worked');
    expect(md).not.toContain('## What to avoid');
  });

  it('uses the CLAUDE.md title and preamble for the claude format', () => {
    const md = renderLearningExport({ format: 'claude', generatedAt: '2026-06-06T00:00:00Z' });
    expect(md).toContain('# Project Guidance for Claude Code');
    expect(md).toContain('Generated by DashClaw on 2026-06-06T00:00:00Z');
  });

  it('renders recommendations sorted by confidence with guidance bullets', () => {
    const md = renderLearningExport({
      format: 'agents',
      recommendations: [
        { action_type: 'deploy', confidence: 60, sample_size: 4, guidance: ['Run tests before deploy'] },
        { action_type: 'apply', agent_id: 'bot1', confidence: 92, sample_size: 12, guidance: ['Prefer small diffs'], hints: { avg_duration_ms: 1200 } },
      ],
    });
    const applyIdx = md.indexOf('### apply');
    const deployIdx = md.indexOf('### deploy');
    expect(applyIdx).toBeGreaterThan(-1);
    expect(deployIdx).toBeGreaterThan(-1);
    // Higher confidence (apply, 92%) comes before lower (deploy, 60%)
    expect(applyIdx).toBeLessThan(deployIdx);
    expect(md).toContain('92% confidence, 12 samples, agent: bot1');
    expect(md).toContain('- Prefer small diffs');
    expect(md).toContain('_Signals: avg_duration_ms: 1200_');
  });

  it('coerces object-shaped guidance entries to text', () => {
    const md = renderLearningExport({
      format: 'agents',
      recommendations: [{ action_type: 'review', confidence: 80, guidance: [{ text: 'Read the diff first' }] }],
    });
    expect(md).toContain('- Read the diff first');
  });

  it('splits decisions into worked vs avoid by outcome', () => {
    const md = renderLearningExport({
      format: 'agents',
      decisions: [
        { decision: 'Cached the query', context: 'hot path', reasoning: 'p95 latency', outcome: 'success' },
        { decision: 'Skipped validation', context: 'user input', outcome: 'failed' },
        { decision: 'Pending thing', outcome: 'pending' },
      ],
    });
    expect(md).toContain('## Decisions that worked');
    expect(md).toContain('- **Cached the query** — hot path _(why: p95 latency)_');
    expect(md).toContain('## What to avoid');
    expect(md).toContain('- **Skipped validation** did not work: user input');
    // pending decisions appear in neither section
    expect(md).not.toContain('Pending thing');
  });
});
