#!/usr/bin/env node

/**
 * DashClaw interactive setup.
 *
 * One command to go from zero to a truthful local/cloud-ready summary:
 *   node scripts/setup.mjs
 *
 * Handles: env config, dependency install, database migrations, build.
 * Cross-platform (Windows, Mac, Linux). Safe to re-run.
 */

process.on('unhandledRejection', (reason) => {
  console.error('Unhandled Rejection:', reason);
  process.exit(1);
});

import fs from 'node:fs';
import crypto from 'node:crypto';
import { execFileSync, spawn } from 'node:child_process';
import readline from 'node:readline';
import { getAuthConfig } from '../app/lib/authConfig.mjs';
import {
  buildSetupMigrationCommands,
  SETUP_MIGRATION_SCRIPTS,
} from '../app/lib/setup/runtime-prerequisites.mjs';
import { parseSetupArgs } from './lib/setup-args.mjs';

const cliArgs = parseSetupArgs(process.argv.slice(2));

function ask(question) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function askSecret(question) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const onData = (char) => {
    const text = String(char);
    if (text === '\n' || text === '\r' || text === '\u0004') {
      process.stdout.write('\n');
      return;
    }
    const prompt = `${question}${'*'.repeat(rl.line.length)}`;
    process.stdout.write(`\x1B[2K\x1B[200D${prompt}`);
  };

  return new Promise((resolve) => {
    process.stdin.on('data', onData);
    rl.question(question, (answer) => {
      process.stdin.removeListener('data', onData);
      rl.close();
      resolve(answer.trim());
    });
  });
}

// New prompts MUST use askOr so they are non-interactive-safe when --yes is set.
function askOr(question, fallback) {
  if (cliArgs.yes) return Promise.resolve(fallback);
  return ask(question);
}

function log(msg) {
  if (cliArgs.json) {
    process.stderr.write(`${msg}\n`);
  } else {
    console.log(msg);
  }
}

function banner(text) {
  const line = '='.repeat(48);
  log(`\n  ${line}\n   ${text}\n  ${line}\n`);
}

function step(n, total, msg) {
  log(`\n  [${n}/${total}] ${msg}\n`);
}

function ok(msg) {
  log(`  [ok] ${msg}`);
}

function warn(msg) {
  log(`  [warn] ${msg}`);
}

function fail(msg) {
  process.stderr.write(`  [fail] ${msg}\n`);
}

function run(cmd, args, opts = {}) {
  try {
    // In --json mode route child stdout to our stderr so that stdout remains
    // exactly one JSON line (the final result object).
    const childStdio = cliArgs.json ? ['inherit', process.stderr, 'inherit'] : 'inherit';
    execFileSync(cmd, args, { stdio: childStdio, shell: true, ...opts });
    return true;
  } catch {
    return false;
  }
}

function runQuiet(cmd, args, opts = {}) {
  try {
    const stdout = execFileSync(cmd, args, {
      stdio: ['ignore', 'pipe', 'pipe'],
      encoding: 'utf8',
      shell: false,
      ...opts,
    });
    return { ok: true, stdout: String(stdout || '').trim() };
  } catch (error) {
    return {
      ok: false,
      stdout: String(error.stdout || '').trim(),
      stderr: String(error.stderr || '').trim(),
    };
  }
}

function parseEnvFile(text) {
  const env = {};
  for (const line of text.split(/\r?\n/)) {
    const parsed = parseEnvLine(line);
    if (parsed) env[parsed.key] = parsed.value;
  }
  return env;
}

function parseEnvLine(line) {
  const trimmed = line.trim();
  if (!isEnvAssignment(trimmed)) return null;
  const idx = trimmed.indexOf('=');
  return {
    key: trimmed.slice(0, idx).trim(),
    value: unquoteEnvValue(trimmed.slice(idx + 1).trim()),
  };
}

function isEnvAssignment(line) {
  return Boolean(line) && !line.startsWith('#') && line.includes('=');
}

function unquoteEnvValue(value) {
  const quoted = (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  );
  return quoted ? value.slice(1, -1).replace(/\\"/g, '"').replace(/\\'/g, "'") : value;
}

function formatEnvValue(value) {
  const text = String(value ?? '');
  if (!/[\s"'#]/.test(text)) return text;
  return `"${text.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function writeEnvFile(env) {
  const order = [
    'DASHCLAW_MODE',
    'NEXT_PUBLIC_DASHCLAW_MODE',
    'DATABASE_URL',
    'DASHCLAW_DB_DRIVER',
    'NEXTAUTH_URL',
    'NEXTAUTH_SECRET',
    'DASHCLAW_LOCAL_ADMIN_PASSWORD',
    'DASHCLAW_API_KEY',
    'DASHCLAW_API_KEY_ORG',
    'ENCRYPTION_KEY',
    'CRON_SECRET',
  ];
  const lines = [`# Generated by scripts/setup.mjs on ${new Date().toISOString()}`];
  for (const key of order) {
    if (env[key] != null) lines.push(`${key}=${formatEnvValue(env[key])}`);
  }
  const extras = Object.keys(env).filter((key) => !order.includes(key)).sort();
  if (extras.length) {
    lines.push('', '# Additional settings');
    for (const key of extras) lines.push(`${key}=${formatEnvValue(env[key])}`);
  }
  fs.writeFileSync('.env.local', `${lines.join('\n')}\n`, 'utf8');
}

function b64url(n) {
  return crypto
    .randomBytes(n)
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/g, '');
}

function redactSecret(value, keep = 4) {
  if (!value) return '(unset)';
  const text = String(value);
  if (text.length <= keep) return '*'.repeat(text.length);
  return `${'*'.repeat(Math.max(8, text.length - keep))}${text.slice(-keep)}`;
}

function describeSignInMethods(authConfig) {
  const methods = [];
  if (authConfig.hasLocalPassword) methods.push('local admin password');
  for (const provider of authConfig.oauthProviders) methods.push(provider.name);
  return methods;
}

async function runAsync(cmd, args, opts = {}) {
  return new Promise((resolve) => {
    let child;
    try {
      child = spawn(cmd, args, { shell: true, stdio: 'pipe', ...opts });
    } catch (error) {
      resolve({ code: 1, stderr: error.message || 'spawn error' });
      return;
    }
    let stderr = '';
    child.stderr?.on('data', (data) => {
      stderr += String(data);
    });
    child.on('close', (code) => resolve({ code, stderr }));
    child.on('error', () => resolve({ code: 1, stderr: 'spawn error' }));
  });
}

async function chooseDatabaseUrl(env) {
  const dockerInstalled = runQuiet('docker', ['--version']).ok;

  if (cliArgs.databaseUrl) {
    env.DATABASE_URL = cliArgs.databaseUrl;
    return { dockerInstalled };
  }

  if (!env.DATABASE_URL) {
    if (cliArgs.yes) {
      throw new Error(
        'Non-interactive mode (--yes) requires --database-url or an existing DATABASE_URL in .env.local.',
      );
    }
    while (!env.DATABASE_URL) {
      printDatabaseChoices(dockerInstalled);
      const choice = await ask('  Choose [1/2/3]: ');
      await applyDatabaseChoice(choice, env, dockerInstalled);
    }
  }

  return { dockerInstalled };
}

function printDatabaseChoices(dockerInstalled) {
  log('  You need a PostgreSQL database. Pick one:\n');
  printDockerChoice(dockerInstalled);
  log('  [2] Neon (free cloud Postgres)');
  log('      Sign up at https://neon.tech, create a project, copy the URL.\n');
  log('  [3] Other Postgres');
  log('      Paste any postgresql:// connection string.\n');
}

function printDockerChoice(dockerInstalled) {
  if (dockerInstalled) {
    log('  [1] Local Docker (fastest for dev)');
    log("      Requires Docker Desktop. We'll start it for you.\n");
  } else {
    log('  [1] Local Docker (unavailable)');
    log('      Docker was not found on this machine. Use Neon or another Postgres URL instead.\n');
  }
}

async function applyDatabaseChoice(choice, env, dockerInstalled) {
  if (choice === '1') return applyDockerDatabaseChoice(env, dockerInstalled);
  if (choice === '2' || choice === '3') return applyPostgresUrlChoice(env);
  warn('Invalid choice. Enter 1, 2, or 3.');
}

async function applyDockerDatabaseChoice(env, dockerInstalled) {
  if (!dockerInstalled) {
    warn('Docker is not installed. Install Docker Desktop or choose Neon/Other Postgres.');
    return;
  }

  log('\n  Starting Docker Postgres...');
  if (!run('docker', ['compose', 'up', '-d', 'db'])) {
    warn('Docker was found, but DashClaw could not start the local database.');
    log('  Next step: start Docker Desktop, then re-run this step or choose Neon/Other Postgres.');
    return;
  }

  env.DATABASE_URL = 'postgresql://dashclaw:dashclaw@localhost:5432/dashclaw';
  ok('Local Postgres is running on localhost:5432');
}

async function applyPostgresUrlChoice(env) {
  const url = await ask('  Paste your PostgreSQL URL: ');
  if (!url || !url.startsWith('postgresql://')) {
    warn('Invalid URL. It must start with postgresql://');
    return;
  }
  env.DATABASE_URL = url;
  ok('Database URL saved');
}

// Set only when THIS RUN created the password. The --json payload must never
// echo a pre-existing password from .env.local back to a parent process.
let generatedAdminPassword = null;

async function maybeConfigureLocalAdminPassword(env) {
  const authConfig = getAuthConfig(env);
  if (authConfig.hasLocalPassword) {
    ok('Local admin password already set');
    return;
  }

  const methods = describeSignInMethods(authConfig);
  if (methods.length > 0) {
    ok(`Dashboard sign-in already configured via ${methods.join(', ')}`);
    return;
  }

  log('  DashClaw needs a dashboard sign-in method.');
  log('  For solo/local use, the easiest path is a local admin password.');
  if (cliArgs.yes) {
    env.DASHCLAW_LOCAL_ADMIN_PASSWORD = b64url(18);
    generatedAdminPassword = env.DASHCLAW_LOCAL_ADMIN_PASSWORD;
    ok(`Local admin password: ${env.DASHCLAW_LOCAL_ADMIN_PASSWORD} (printed ONCE — written only to .env.local)`);
    return;
  }

  const answer = await ask('  Set a local admin password now? [Y/n]: ');
  if (answer.toLowerCase() === 'n') {
    warn('Skipped dashboard sign-in setup. You will need DASHCLAW_LOCAL_ADMIN_PASSWORD or OAuth before you can sign in.');
    return;
  }

  while (!env.DASHCLAW_LOCAL_ADMIN_PASSWORD) {
    const password = await askSecret('  Choose a local admin password (min 12 chars): ');
    if (!password) {
      warn('Password was blank. Setup will continue, but dashboard sign-in will stay unconfigured.');
      return;
    }
    if (password.length < 12) {
      warn('Use at least 12 characters.');
      continue;
    }

    const confirm = await askSecret('  Confirm password: ');
    if (password !== confirm) {
      warn('Passwords did not match. Try again.');
      continue;
    }

    env.DASHCLAW_LOCAL_ADMIN_PASSWORD = password;
    generatedAdminPassword = password;
    ok('Local admin password saved to .env.local');
  }
}

const TOTAL_SETUP_STEPS = 6;

function loadLocalEnv() {
  const envPath = '.env.local';
  return fs.existsSync(envPath) ? parseEnvFile(fs.readFileSync(envPath, 'utf8')) : {};
}

async function configureDatabase(env) {
  step(1, TOTAL_SETUP_STEPS, 'Database connection');
  // An explicit --database-url wins over EVERYTHING (pre-existing .env.local,
  // process env). Without this, the keep-existing path below silently ignored
  // the flag and the installer could migrate the wrong database.
  if (cliArgs.databaseUrl) {
    env.DATABASE_URL = cliArgs.databaseUrl;
    ok(`Using DATABASE_URL from --database-url (${cliArgs.databaseUrl.replace(/\/\/[^@]+@/, '//***@').replace(/\?.*/, '')})`);
    const { dockerInstalled } = await chooseDatabaseUrl(env);
    return dockerInstalled;
  }
  if (process.env.DATABASE_URL && process.env.DATABASE_URL !== env.DATABASE_URL) {
    env.DATABASE_URL = process.env.DATABASE_URL;
    ok(`Using DATABASE_URL from environment (${env.DATABASE_URL.replace(/\/\/[^@]+@/, '//***@').replace(/\?.*/, '')})`);
  } else if (env.DATABASE_URL) {
    const masked = env.DATABASE_URL.replace(/\/\/[^@]+@/, '//***@').replace(/\?.*/, '');
    ok(`DATABASE_URL already set (${masked})`);
    const change = await askOr('  Change it? [y/N]: ', 'n');
    if (change.toLowerCase() === 'y') delete env.DATABASE_URL;
  }

  const { dockerInstalled } = await chooseDatabaseUrl(env);
  return dockerInstalled;
}

async function configureDeploymentUrl(env) {
  step(2, TOTAL_SETUP_STEPS, 'Deployment mode');
  let deployUrl = env.NEXTAUTH_URL;
  if (!deployUrl || deployUrl === 'http://localhost:3000') {
    if (cliArgs.yes) {
      deployUrl = 'http://localhost:3000';
    } else {
      log('  How will you access the dashboard?\n');
      log('  [1] Local only (http://localhost:3000)');
      log('      Run "npm run dev" on this machine.\n');
      log('  [2] Cloud (Vercel, Railway, etc.)');
      log('      Access from anywhere.\n');

      const deployChoice = await ask('  Choose [1/2]: ');
      if (deployChoice === '2') {
        const url = await ask('  Your deployment URL (for example https://my-dashclaw.vercel.app): ');
        if (url && url.startsWith('http')) {
          deployUrl = url.replace(/\/+$/, '');
        } else {
          warn('Invalid URL. Defaulting to http://localhost:3000');
          deployUrl = 'http://localhost:3000';
        }
      } else {
        deployUrl = 'http://localhost:3000';
      }
    }
  } else {
    ok(`Dashboard URL: ${deployUrl}`);
  }
  return deployUrl;
}

async function configureSecretsAndLogin(env, deployUrl) {
  step(3, TOTAL_SETUP_STEPS, 'Secrets and dashboard login');
  if (!env.DASHCLAW_MODE) env.DASHCLAW_MODE = 'self_host';
  if (!env.NEXT_PUBLIC_DASHCLAW_MODE) env.NEXT_PUBLIC_DASHCLAW_MODE = env.DASHCLAW_MODE;
  env.NEXTAUTH_URL = deployUrl;
  if (!env.NEXTAUTH_SECRET) env.NEXTAUTH_SECRET = b64url(32);
  const apiKeyWasGenerated = !env.DASHCLAW_API_KEY;
  if (apiKeyWasGenerated) env.DASHCLAW_API_KEY = `oc_live_${crypto.randomBytes(24).toString('hex')}`;
  if (!env.ENCRYPTION_KEY) env.ENCRYPTION_KEY = b64url(32).slice(0, 32);
  if (!env.CRON_SECRET) env.CRON_SECRET = crypto.randomBytes(32).toString('hex');

  await maybeConfigureLocalAdminPassword(env);

  writeEnvFile(env);
  ok('Wrote .env.local');
  if (apiKeyWasGenerated) {
    // First run only: show the full key once so the user can save it.
    // On re-runs, .env.local already holds the key and we only print the
    // redacted summary below to avoid leaking it in scrollback.
    log('');
    log("  API Key (save this — it won't be shown in full again):");
    log(`    ${env.DASHCLAW_API_KEY}`);
  }
  log(`\n  API key: ${redactSecret(env.DASHCLAW_API_KEY)}`);
  log(`  Dashboard URL: ${deployUrl}`);
}

function installDependencies() {
  step(4, TOTAL_SETUP_STEPS, 'Installing dependencies');
  if (!run('npm', ['install'])) {
    fail('npm install failed. Check your network connection and npm logs above.');
    process.exit(1);
  }
  ok('Dependencies installed');
}

async function runMigrationsAndCheckSetup(env) {
  step(5, TOTAL_SETUP_STEPS, 'Running database migrations');
  const migrationEnv = { ...process.env, ...env };
  const migrationResults = [];
  for (const script of SETUP_MIGRATION_SCRIPTS) {
    migrationResults.push(await runMigrationScript(script, migrationEnv));
  }

  const migrationFailures = migrationResults.filter((result) => !result.ok);
  if (migrationFailures.length === 0) {
    ok('All migrations completed');
  } else {
    warn(`${migrationFailures.length} migration(s) failed. DashClaw is not database-ready yet.`);
  }

  const { getSetupStatus } = await import('../app/lib/setupStatus.mjs');
  const setupStatus = await getSetupStatus(migrationEnv);
  return { migrationEnv, migrationResults, migrationFailures, setupStatus };
}

async function runMigrationScript(script, migrationEnv) {
  const frames = ['-', '\\', '|', '/'];
  const name = script.replace('scripts/', '').replace('.mjs', '');
  const start = Date.now();
  let frame = 0;
  const out = cliArgs.json ? process.stderr : process.stdout;
  const spinner = setInterval(() => {
    const elapsed = Math.floor((Date.now() - start) / 1000);
    out.write(`\r  ${frames[frame++ % frames.length]} Running ${name}... (${elapsed}s)`);
  }, 100);

  const result = await runAsync('node', [script], { env: migrationEnv });
  clearInterval(spinner);
  return formatMigrationResult(script, name, result);
}

function formatMigrationResult(script, name, result) {
  const out = cliArgs.json ? process.stderr : process.stdout;
  if (result.code === 0) {
    out.write(`\r  [ok] ${name}${' '.repeat(30)}\n`);
    return { script, ok: true };
  }
  out.write(`\r  [fail] ${name}${' '.repeat(30)}\n`);
  const firstLine = result.stderr.trim().split('\n')[0];
  if (firstLine) log(`     ${firstLine}`);
  return { script, ok: false, error: firstLine || 'Migration failed' };
}

function buildDashboard(migrationEnv) {
  step(6, TOTAL_SETUP_STEPS, 'Building the dashboard');
  const buildOk = run('npm', ['run', 'build'], { env: migrationEnv });
  if (buildOk) {
    ok('Build completed');
  } else {
    warn('Build failed. Fix the error above, then rerun npm run build.');
  }
  return buildOk;
}

function setupReadiness({ env, setupStatus, buildOk }) {
  const authConfig = getAuthConfig(env);
  const databaseReady = Boolean(setupStatus?.configured);
  const signInReady = authConfig.hasAnySignInMethod;
  return {
    authConfig,
    signInMethods: describeSignInMethods(authConfig),
    databaseReady,
    signInReady,
    fullyReady: databaseReady && signInReady && buildOk,
  };
}

function printSuccessSummary({ migrationResults, buildOk }) {
  log('  What succeeded:');
  ok('.env.local was written with generated secrets');
  ok('Dependencies installed');
  if (migrationResults.some((result) => result.ok)) {
    ok(`${migrationResults.filter((result) => result.ok).length}/${migrationResults.length} migration scripts completed`);
  }
  if (buildOk) ok('Next.js production build completed');
}

function printCurrentStatus({ setupStatus, databaseReady, signInReady, signInMethods, migrationFailures, buildOk }) {
  log('\n  Current status:');
  if (databaseReady) {
    ok('Database is reachable and core setup tables exist');
  } else if (setupStatus?.reason === 'connection_error') {
    warn('Database is not reachable yet. /api/setup/status would report connection_error.');
  } else if (setupStatus?.reason === 'no_tables') {
    warn(`Database is reachable, but ${setupStatus.missing_tables} core table(s) are still missing.`);
  } else {
    warn(setupStatus?.message || 'DashClaw setup status could not be verified.');
  }

  if (signInReady) {
    ok(`Dashboard sign-in is available via ${signInMethods.join(', ')}`);
  } else {
    warn('Dashboard sign-in is not configured yet.');
  }

  if (migrationFailures.length > 0) {
    warn(`Failed migrations: ${migrationFailures.map((result) => result.script.replace('scripts/', '')).join(', ')}`);
  }
  if (!buildOk) {
    warn('Build step did not finish cleanly.');
  }
}

function printDatabaseNextSteps({ setupStatus, env, dockerInstalled, nextStepNumber }) {
  if (setupStatus?.reason === 'connection_error') {
    if (env.DATABASE_URL?.includes('localhost')) {
      log(`  ${nextStepNumber}. Start or verify your local Postgres server.`);
      if (dockerInstalled) {
        log('     Command: docker compose up -d db');
      }
    } else {
      log(`  ${nextStepNumber}. Verify that DATABASE_URL points to a reachable Postgres instance.`);
    }
    nextStepNumber += 1;
  }

  log(`  ${nextStepNumber}. Re-run the migration step after the database is reachable:`);
  for (const command of buildSetupMigrationCommands()) {
    log(`     ${command}`);
  }
  return nextStepNumber + 1;
}

function printReadyNextSteps({ deployUrl, signInMethods, nextStepNumber }) {
  const isCloud = deployUrl !== 'http://localhost:3000';
  if (isCloud) {
    log(`  ${nextStepNumber}. Push this repo to GitHub, add the values from .env.local to your host, and deploy.`);
    nextStepNumber += 1;
    log(`  ${nextStepNumber}. Open ${deployUrl}/dashboard and sign in with ${signInMethods[0]}.`);
  } else {
    log(`  ${nextStepNumber}. Start the app locally.`);
    log('     Command: npm run dev');
    nextStepNumber += 1;
    log(`  ${nextStepNumber}. Open http://localhost:3000/dashboard and sign in with ${signInMethods[0]}.`);
  }
}

function printNextSteps({ databaseReady, signInReady, buildOk, setupStatus, env, dockerInstalled, deployUrl, signInMethods }) {
  log('\n  Next steps:');
  let nextStepNumber = 1;

  if (!databaseReady) {
    nextStepNumber = printDatabaseNextSteps({ setupStatus, env, dockerInstalled, nextStepNumber });
  }

  if (!signInReady) {
    log(`  ${nextStepNumber}. Configure a dashboard login method.`);
    log('     Easiest local path: set DASHCLAW_LOCAL_ADMIN_PASSWORD in .env.local and rerun setup.');
    log('     Team path: add GitHub, Google, or OIDC environment variables.');
    nextStepNumber += 1;
  }

  if (!buildOk) {
    log(`  ${nextStepNumber}. Re-run the build once the error above is fixed.`);
    log('     Command: npm run build');
    nextStepNumber += 1;
  }

  if (databaseReady && signInReady && buildOk) {
    printReadyNextSteps({ deployUrl, signInMethods, nextStepNumber });
  } else {
    log(`  ${nextStepNumber}. Re-run node scripts/setup.mjs after you fix the items above.`);
  }
}

function printAgentSnippet(env, deployUrl) {
  log('\n  Agent connection snippet:\n');
  log(`    DASHCLAW_BASE_URL=${deployUrl}`);
  log(`    DASHCLAW_API_KEY=${env.DASHCLAW_API_KEY}`);
  log('    DASHCLAW_AGENT_ID=my-agent\n');
}

function printSetupReport(context) {
  const readiness = setupReadiness(context);
  banner(readiness.fullyReady ? 'Setup Complete' : 'Setup Not Finished Yet');
  printSuccessSummary(context);
  printCurrentStatus({ ...context, ...readiness });
  printNextSteps({ ...context, ...readiness });
  printAgentSnippet(context.env, context.deployUrl);
}

async function main() {
  banner('DashClaw Setup');
  const env = loadLocalEnv();
  const dockerInstalled = await configureDatabase(env);
  const deployUrl = await configureDeploymentUrl(env);
  await configureSecretsAndLogin(env, deployUrl);
  installDependencies();
  const migrationState = await runMigrationsAndCheckSetup(env);
  // Non-interactive callers (npx dashclaw up) trust ok:true to mean the DB is
  // genuinely ready — an unreachable database must be a hard failure, not a
  // warn-and-continue status line.
  if (cliArgs.yes && !migrationState.setupStatus?.configured) {
    throw new Error(
      `Database is not ready after setup (${migrationState.setupStatus?.reason || 'unknown'}). ` +
      'Check that the configured DATABASE_URL is reachable, then re-run.'
    );
  }
  const buildOk = buildDashboard(migrationState.migrationEnv);
  printSetupReport({ env, deployUrl, dockerInstalled, buildOk, ...migrationState });
  if (cliArgs.json) {
    console.log(JSON.stringify({
      ok: true,
      apiKey: env.DASHCLAW_API_KEY,
      adminPassword: generatedAdminPassword,
    }));
  }
}

main().catch((err) => {
  if (cliArgs.json) {
    // Guarantee exactly one JSON line on stdout even on failure.
    console.log(JSON.stringify({ ok: false, error: err.message }));
  } else {
    process.stderr.write(`  [fail] ${err.message}\n`);
  }
  process.exit(1);
});
