/**
 * living-merge — single source of truth for which repo paths are GENERATED
 * projections of source (and therefore must be regenerated on merge, never
 * hand-merged).
 *
 * Owned by LivingCode; consumed by:
 *   - the `.gitattributes` `merge=regenerate` block (generated by install.ts)
 *   - the post-merge / post-rewrite git hooks (which run regenerate-all)
 *   - the overlap-signal SessionStart hook (to FILTER OUT generated paths so
 *     only true AUTHORED-file collisions across worktrees are surfaced)
 *
 * Anything NOT listed here is AUTHORED and protected: a merge conflict on it
 * surfaces normally and the overlap signal warns about it. Do NOT add
 * hand-authored files here (SDKs, CLI, plugin manifests, the canonical `hooks/`
 * source, the authored `references` + `scripts` dirs under each skill, lockfiles,
 * `.claude/CODEBASE_MAP.md`) — marking those `merge=regenerate` would silently
 * DISCARD hand edits on merge.
 *
 * Derived from (and kept in lockstep with):
 *   - scripts/livingcode-refresh.mjs        (GENERATED_PATH_RE + the 22 outputs)
 *   - scripts/lib/run-pre-commit-checks.mjs (the `stage-artifacts` path list)
 *   - scripts/generate-api-inventory.mjs    (docs/api-inventory.*)
 *   - scripts/generate-openapi.mjs          (docs/openapi/critical-stable.openapi.json)
 * Verified 2026-06-06 (STAGE 0 discovery).
 */

/**
 * The single "regenerate everything from source" entry point. Kept as a plain
 * `.mjs` (no tsx) so the git hooks and merge driver that invoke it have zero
 * transpiler dependency at merge/hook time.
 */
export const REGENERATE_COMMAND = [
  'node',
  'scripts/living-merge/regenerate-all.mjs',
] as const;

/**
 * Gitattributes-style path patterns for every generated projection.
 * `dir/**` matches the whole subtree; a bare path matches that exact file.
 */
export const GENERATED_PATTERNS: readonly string[] = [
  // ── LivingCode shape model (python `livingcode emit`) ──────────────────────
  // NB: list the 3 generated files explicitly — app/lib/doctor/generated/ also
  // contains a HAND-AUTHORED README.md, which must NOT be merge=regenerate.
  'app/lib/doctor/generated/shape.json',
  'app/lib/doctor/generated/last-snapshot.json',
  'app/lib/doctor/generated/checks-from-shape.mjs',
  'mcp-server/lib/routes-inventory.generated.json',
  // ── Living dashboard (python `livingcode emit dashboard`) ──────────────────
  'public/livingcode/index.html',
  // ── platform-intelligence skill: ONLY SKILL.md is generated;
  //    its references/ + scripts/ are AUTHORED sources (excluded). ────────────
  'public/downloads/dashclaw-platform-intelligence/SKILL.md',
  // ── distributable bundle zips + their content-hash manifests ───────────────
  'public/downloads/dashclaw-platform-intelligence.zip',
  'public/downloads/dashclaw-platform-intelligence.zip.manifest',
  'public/downloads/dashclaw-governance.zip',
  'public/downloads/dashclaw-governance.zip.manifest',
  'public/downloads/dashclaw-governance-plugin.zip',
  'public/downloads/dashclaw-governance-plugin.zip.manifest',
  'public/downloads/dashclaw-claude-code-hooks.zip',
  'public/downloads/dashclaw-claude-code-hooks.zip.manifest',
  // ── plugin skill mirrors (regenerated copies of website source-of-truth) ───
  'plugins/dashclaw/skills/dashclaw-platform-intelligence/**',
  'plugins/dashclaw/skills/dashclaw-governance/**',
  // ── plugin hook mirrors (regenerated copies of the canonical hooks/ source) ─
  'plugins/dashclaw/hooks/dashclaw_pretool.py',
  'plugins/dashclaw/hooks/dashclaw_posttool.py',
  'plugins/dashclaw/hooks/dashclaw_stop.py',
  'plugins/dashclaw/hooks/dashclaw_code_session_reporter.py',
  'plugins/dashclaw/hooks/dashclaw_session_digest.py',
  'plugins/dashclaw/hooks/dashclaw_agent_intel/**',
  // ── docs projections (generate-api-inventory.mjs + generate-openapi.mjs) ────
  'docs/api-inventory.json',
  'docs/api-inventory.md',
  'docs/openapi/critical-stable.openapi.json',
];

/** Normalize to forward slashes, repo-root-relative, no leading `./` or `/`. */
export function normalizePath(p: string): string {
  return p.replace(/\\/g, '/').replace(/^\.\//, '').replace(/^\/+/, '');
}

/** True if `relPath` (repo-root-relative) is a generated projection. */
export function isGenerated(relPath: string): boolean {
  const path = normalizePath(relPath);
  for (const pattern of GENERATED_PATTERNS) {
    if (pattern.endsWith('/**')) {
      const prefix = pattern.slice(0, -3); // drop "/**"
      if (path === prefix || path.startsWith(prefix + '/')) return true;
    } else if (path === pattern) {
      return true;
    }
  }
  return false;
}

/** Inverse of {@link isGenerated} — convenience for overlap filtering. */
export function isAuthored(relPath: string): boolean {
  return !isGenerated(relPath);
}
